# Generated by Django 6.0.4 on 2026-04-24 08:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Phone number for login and identification",
                        max_length=15,
                        unique=True,
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[("CUSTOMER", "Customer"), ("RIDER", "Rider")],
                        default="CUSTOMER",
                        help_text="Type of user: Customer or Rider",
                        max_length=10,
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True,
                        help_text="Profile photo of the user",
                        null=True,
                        upload_to="profile_photos/",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the user account is active"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FOOD", "Food"),
                            ("PARCEL", "Parcel"),
                            ("DOCUMENT", "Document"),
                        ],
                        default="FOOD",
                        max_length=10,
                    ),
                ),
                (
                    "priority_weight",
                    models.IntegerField(
                        default=10,
                        help_text="Higher weight means higher priority (food gets 30)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PICKED_UP", "Picked Up"),
                            ("IN_TRANSIT", "In Transit"),
                            ("DELIVERED", "Delivered"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                (
                    "pickup_latitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Pickup location latitude",
                        max_digits=9,
                    ),
                ),
                (
                    "pickup_longitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Pickup location longitude",
                        max_digits=9,
                    ),
                ),
                (
                    "dropoff_latitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Dropoff location latitude",
                        max_digits=9,
                    ),
                ),
                (
                    "dropoff_longitude",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Dropoff location longitude",
                        max_digits=9,
                    ),
                ),
                ("pickup_address", models.CharField(blank=True, max_length=255)),
                ("dropoff_address", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "CUSTOMER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"user_type": "RIDER"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rider_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TripMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Distance in kilometers",
                        max_digits=6,
                    ),
                ),
                (
                    "expected_duration",
                    models.PositiveIntegerField(
                        help_text="Expected duration in minutes"
                    ),
                ),
                (
                    "actual_duration",
                    models.PositiveIntegerField(
                        blank=True, help_text="Actual duration in minutes", null=True
                    ),
                ),
                (
                    "wait_time_minutes",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Wait time calculated by geofence logic",
                        max_digits=5,
                    ),
                ),
                (
                    "base_fare",
                    models.DecimalField(
                        decimal_places=2, help_text="Base fee", max_digits=8
                    ),
                ),
                (
                    "distance_fare",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Fee based on distance",
                        max_digits=8,
                    ),
                ),
                (
                    "delay_fare",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Additional fee for delays",
                        max_digits=8,
                    ),
                ),
                (
                    "total_fare",
                    models.DecimalField(
                        decimal_places=2, help_text="Total fare charged", max_digits=8
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_metrics",
                        to="core.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "make_model",
                    models.CharField(
                        help_text="Vehicle make and model (e.g., 'Veloka MTB')",
                        max_length=100,
                    ),
                ),
                (
                    "frame_number",
                    models.CharField(
                        help_text="Unique frame/chassis number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "last_maintenance_date",
                    models.DateField(
                        blank=True, help_text="Last maintenance date", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Rider who owns this vehicle",
                        limit_choices_to={"user_type": "RIDER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LocationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "rider",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "RIDER"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["rider", "-timestamp"],
                        name="core_locati_rider_i_d24735_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        help_text="Rating from 1 to 5 stars",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, help_text="Optional review comment"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="core.order",
                    ),
                ),
            ],
            options={
                "unique_together": {("order",)},
            },
        ),
    ]
